### PR TITLE
no hidden part of unicode code-point range

### PR DESCRIPTION
**Pull request by charlie-wong**

### CODE REVIEW

**Comment by mattlag** [comment]
Thank you! Changes look good, i'll post it to unicode.ninja soon :-)

**Comment by charlie-wong** [comment]
I see it already online and looks good, my pleasure! 😀

**Comment by charlie-wong** [comment]
> Thank you! Changes look good, i'll post it to unicode.ninja soon :-)

I see it already online and looks goo, my pleasure! 😀

**Comment by charlie-wong** [comment]
> Thank you! Changes look good, i'll post it to unicode.ninja soon :-)

I see it already online and looks good, my pleasure! 😀

**Pull request merged**
